name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    env:
      IMAGE_SERVICE_ORDER_NAME: mochaaii/bwamicro_service_order
      IMAGE_SERVICE_ORDER_TAG: latest
      IMAGE_WEBSERVER_ORDER_NAME: mochaaii/bwamicro_webserver_order
      IMAGE_WEBSERVER_ORDER_TAG: latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image Service Order
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_SERVICE_ORDER_NAME }}:${{ env.IMAGE_SERVICE_ORDER_TAG }}

      - name: Build and Push Docker Image Webserver Order
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.webserver
          push: true
          tags: ${{ env.IMAGE_WEBSERVER_ORDER_NAME }}:${{ env.IMAGE_WEBSERVER_ORDER_TAG }}

      - name: Logout from Docker Hub
        run: docker logout
